### ISSUE TITLE
Principles of software engineering

### ISSUE THREAD

**Issue by steve-crouch** [Southampton-RSG-Training/dirac-software-engineering-old#1]
Software development lifecycle [Alpha]
Python refresher []
Introduction to programming paradigms []
Object-orientated programming []
Functional Programming []
Best practices in writing code [Alpha]

**Comment by PipGrylls** [comment]
Software development lifecycle, @steve-crouch 3 days effort, review @jag1g13 
Python refresher, @jag1g13 2 days effort, review @smangham 
Introduction to programming paradigms, @jag1g13 1 day effort, review @PipGrylls @smangham
Object-orientated programming, @jag1g13 3 days effort, review @PipGrylls @smangham
Functional Programming, @jag1g13  3 days effort, review @PipGrylls @smangham
Best practices in writing code, @smangham 4 days effort, review @steve-crouch

**Comment by phillybroadbent** [comment]
Programming Paradigms
•	I found this lesson quite difficult, but everything made sense to me after going through it a couple of times

Object oriented programming
•	I found this lesson the most difficult 
•	Encapsulating behaviour - Member functions living inside a class – I found this a difficult concept to grasp. What’s the difference between a method and a function? (When the function we’re writing doesn’t need access to any data belonging to a particular object?)
•	Relationships between classes - We now have a language construct for grouping data and behaviour related to a single conceptual object – I found this sentence a bit difficult to understand
•	Inheritance - The line super().__init__(name) gets the parent class, then calls the __init__ method, providing the name variable that Person.__init__ requires – this was a bit confusing for me. 
•	From inflammation.models import Patient - I don't think this command has been covered?

Functional programming
•	I found this lesson less difficult than the previous but still challenging
•	Testing impure functions – would you often declare functions inside classes? This confused me a bit

**Comment by steve-crouch** [comment]
First draft of 'Software development lifecycle' complete. @jag1g13 - since you're down as secondary author, could you review when you get a moment?

**Comment by steve-crouch** [comment]
Reviewed and completed, and material ported to new repo using training infrastructure - https://github.com/Southampton-RSG-Training/dirac-software-engineering
